// Application constants

export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const SPECIALIZATION_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const DOCTOR_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const SLOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  BOOKED: 'BOOKED',
  BLOCKED: 'BLOCKED',
};

export const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};

export const CONVERSATION_STAGE = {
  COLLECTING_DETAILS: 'COLLECTING_DETAILS',
  SEARCHING: 'SEARCHING',
  AWAITING_SLOT_SELECTION: 'AWAITING_SLOT_SELECTION',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const CONVERSATION_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
};

export const MESSAGE_ROLE = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
  TOOL_RESULT: 'TOOL_RESULT',
};

export const INTENT = {
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  CHECK_AVAILABILITY: 'CHECK_AVAILABILITY',
  MODIFY_APPOINTMENT: 'MODIFY_APPOINTMENT',
  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
  VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
  GENERAL_QUERY: 'GENERAL_QUERY',
  UNKNOWN: 'UNKNOWN',
};

export const NEXT_ACTION = {
  ASK_CLARIFICATION: 'ASK_CLARIFICATION',
  CALL_FUNCTION: 'CALL_FUNCTION',
  REQUEST_CONFIRMATION: 'REQUEST_CONFIRMATION',
  RESPOND: 'RESPOND',
};

export const CONFIRMATION_STATE = {
  CONFIRMED: 'CONFIRMED',
  DECLINED: 'DECLINED',
  NOT_PROVIDED: 'NOT_PROVIDED',
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

// Time range defaults (HH:mm format)
export const TIME_RANGES = {
  MORNING: { start: '08:00', end: '12:00' },
  AFTERNOON: { start: '12:00', end: '17:00' },
  EVENING: { start: '17:00', end: '20:00' },
};

// Pagination defaults
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

// Rate limiting
export const RATE_LIMITS = {
  AUTH: {
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 5, // 5 attempts
  },
  CHAT: {
    windowMs: 60 * 1000, // 1 minute
    max: 10, // 10 messages
  },
  API: {
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100, // 100 requests
  },
};
